model_list:
  # OpenAI
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: 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

  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: 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

  # Anthropic
  - model_name: claude-3-opus
    litellm_params:
      model: claude-3-opus-20240229
      api_key: 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

  - model_name: claude-3-sonnet
    litellm_params:
      model: claude-3-5-sonnet-20240620
      api_key: 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

  # Google
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-1.5-flash
      api_key: AIzaSyCasbpoNBkmZfuu9IEGhOGc8wxBEJ5Th5c

  # Grok (xAI)
  - model_name: grok
    litellm_params:
      model: xai/grok-3-large
      api_key: xai-syU4GduOod5hAhF8cU0SsolMZjmYuLqoQH2UkOwpWouLfaq9chNY8IaYQthRoTOeJAoqsCDWH090q6Yu

  # Deepseek
  - model_name: deepseek-chat
    litellm_params:
      model: deepseek/deepseek-chat
      api_key: sk-58e53e589fb54751a2cf557f671197f2

general_settings:
  master_key: "metatron123"
  # O LiteLLM requer PostgreSQL para a funcionalidade de geração de chaves
  # String de conexão do banco de dados PostgreSQL do Neon.tech
  database_url: "postgresql://neondb_owner:npg_vK83YqplgezT@ep-floral-unit-a53d3jyc-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"

litellm_settings:
  verbose: False
  cache: False
  callbacks: []
  request_timeout: 300
  drop_params: True
  max_tokens: 8000
  max_parallel_requests: 5

router_settings:
  num_retries: 2
  routing_strategy: "simple-shuffle"
  cache_responses: False

spend_limits:
  global_spend_limit: 100
  currency: "USD"
